version: '3'

services:
  # nestjs-api:
    # build:
    #   context: ./clv2-be
    # ports:
    #   - "4000:4000"
    # environment:
    #   - DB_TYPE=postgres
    #   - DB_HOST=postgres
    #   - DB_PORT=5432
    #   - DB_USERNAME=taidang
    #   - DB_PASSWORD=taidang123
    #   - DB_DATABASE=clv_jwat_taidang
    #   - NODE_ENV=production
    #   - APP_PORT=4000
    #   - BACKEND_DOMAIN=http://localhost:4000
    # depends_on:
    #   - postgres
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: taidang
      POSTGRES_PASSWORD: taidang123
      POSTGRES_DB: clv_jwat_taidang
    volumes:
      - postgres-data:/var/lib/postgresql/data3
volumes:
  postgres-data:
